kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  type: LoadBalancer
  labels:
    component: backend
    environment: prod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: {{ .Values.service.nodePort }} # assume this will also change